<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                             https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <groupId>cat.informaticassa</groupId>
    <artifactId>icfact</artifactId>
    <version>1.0-SNAPSHOT</version>

    <name>ICFact</name>
    <description>Aplicació de facturació per a autònoms i petites empreses.</description>
    <packaging>jar</packaging>

    <properties>
        <!-- Java -->
        <java.version>21</java.version>
        <!-- Codificació -->
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <!-- Plugins -->
        <maven.compiler.plugin.version>3.14.0</maven.compiler.plugin.version>
    </properties>

    <dependencies>
        <!-- Sense dependències de moment -->
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven.compiler.plugin.version}</version>
                <configuration>
                    <release>${java.version}</release>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>